<template>
    <wrapper
        :is="config.wrapper||'el-form-item'"
        :label="config.label"
        :label-width="config.labelWidth||'0px'"
        @click="click"
        @click.native="click"
        class="elementButton"
        :style="config.style"
    >
        <el-button 
            :type="config.buttonType" 
            :icon="config.icon"
            :round="config.shape=='round'||config.round"
            :circle="config.shape=='circle'||config.circle"
            :plain="config.saturation=='plain'?true:false||config.plain"
            :native-type="config.nativeType"
            :title="config.title"
            :size="config.size"
            :class="{noText:!config.textShow}"
            @click="buttonClick"
        >{{config.text}}</el-button>
    </wrapper>
</template>
<script>
    export default {
        props: ['config','form'],
        data(){
            return {
                role:[],
                dept:[],
                user:[]
            }
        },
        created(){
            if(!this.config.query){
                this.$set(this.config,'query',{});
            }
            if(!this.config.priv){
                this.$set(this.config,'priv',{role:[],dept:[],user:[]});
            }            
        },
        mounted(){
            //组件添加删除按钮
            let vue=this,
                span=document.createElement('span');
            span.className="my-close";
            span.addEventListener('click',function(){
                vue.$emit('close',event,vue);
            });
            this.$el.style.position="relative";
            this.$el.appendChild(span);
        },          
        methods:{
            buttonClick: function(event){
                this.$emit('buttonClick',event,this.config);
            },
            click(event){
                if(!this.role.length||!this.user.length){
                    this.my.axiosAll({
                        vue:this,
                        axiosOption:[{
                            url: 'admin/table/table',
                            data:{
                                TABLE_NAME:'roles',
                                fields:'`name` as label,`id` as value',
                            }
                        },{
                            url: 'admin/table/table',
                            data:{
                                TABLE_NAME:'users',
                                fields:'`name` as label,`id` as value',
                            }
                        }],
                        success:function (response,option) {
                            option.vue.$set(option.vue,'role',response[0].data.data);
                            option.vue.$set(option.vue,'user',response[1].data.data);
                            option.vue.emit(event);
                        }
                    });                    
                }else{
                    this.emit(event);
                }
            },
            emit(event){
                this.$emit('config',event,this.config,{
                    textShow:{
                        name:"textShow",
                        type:"elementSwitch",
                        label:"显示文字"
                    },
                    text:{
                        name:"text",
                        type:"elementText",
                        label:"文字"
                    },
                    icon:{
                        name:"icon",
                        type:"elementText",
                        label:"图标"
                    },
                    title:{
                        name:"title",
                        type:"elementText",
                        label:"提示"
                    },
                    buttonType:{
                        name:"buttonType",
                        type:"elementSelect",
                        label:"类型",
                        options:[{
                            label:"默认",
                            value:""
                        },{
                            label:"文本",
                            value:"text"
                        },{
                            label:"主要",
                            value:"primary"
                        },{
                            label:"成功",
                            value:"success"
                        },{
                            label:"信息",
                            value:"info"
                        },{
                            label:"警告",
                            value:"warning"
                        },{
                            label:"危险",
                            value:"danger"
                        }]
                    }, 
                    saturation:{
                        name:"saturation",
                        type:"elementRadio",
                        label:"彩度",
                        options:[{
                            type:'el-radio',
                            value:"",
                            label:"鲜艳"
                        },{
                            type:'el-radio',
                            value:"plain",
                            label:"平淡"
                        }]
                    },
                    shape:{
                        name:"shape",
                        type:"elementSelect",
                        label:"形状",
                        options:[{
                            label:"默认",
                            value:""
                        },{
                            label:"圆形",
                            value:"circle"
                        },{
                            label:"圆角",
                            value:"round"
                        }]
                    },                                   
                    size:{
                        name:"size",
                        type:"elementSelect",
                        label:"尺寸",
                        options:[{
                            label:"默认",
                            value:""
                        },{
                            label:"中等",
                            value:"medium"
                        },{
                            label:"小型",
                            value:"small"
                        },{
                            label:"超小",
                            value:"mini"
                        }]
                    },
                    operator:{
                        name:"operator",
                        type:"elementRadioChange",
                        label:"操作",
                        itemDefault:{
                            label:" "
                        },
                        options:[{
                            type:"el-radio",
                            label:"默认",
                            value:"elementSelect", 
                            config:{
                                type:"elementSelect",
                                name:"script",
                                options:[{
                                    value:"this.save(event,config);",
                                    label:"保存"
                                },{
                                    value:"this.cancel(event,config);",
                                    label:"关闭"
                                },{
                                    value:"this.save(event,config,true);",
                                    label:"保存并关闭"
                                },]
                            }                      
                        },{
                            type:"el-radio",
                            label:"自定义",
                            value:"elementTextarea", 
                            config:{
                                name:"script",
                                type:"elementTextarea",                          
                            }                            
                        }]
                    },
                    query:{
                        type:"elementAddDelete",
                        labelPositionTop:true,
                        name:"query",
                        label:"参数",
                        labels:[{
                            label:"参数名"
                        },{
                            label:"参数值"
                        }],
                        itemDefault:{
                            size:"mini",
                            style:"width:40%;display:inline-block;margin-right:2%",
                        },
                        options:this.config.query//Object.assign({},this.config.query)
                    },
                    priv:{
                        type:"elementComponents",
                        name:"priv",
                        label:"权限",
                        labelPositionTop:true,
                        itemDefault:{
                            size:"small"
                        },                        
                        options:[{
                            type:"elementSelect",
                            name:"role",
                            label:"角色",
                            transfer:true,
                            multiple:true,
                            source:"options",                        
                            options:this.role,
                            config:{
                                type:"elementTransfer",
                                wrapper:"div",
                                name:"role",
                                data:this.role,
                                titles:['未选','已选'],
                                filterable:true 
                            }
                        },{ 
                            type:"elementSelect",
                            name:"dept",
                            label:"部门",
                            transfer:true,
                            multiple:true, 
                            source:"tableField",
                            tableField:{
                                table:"roles",
                                fieldLabel:"name",
                                fieldValue:"id"
                            },
                            options:[{label: "a", value: 1}],
                            config:{
                                type:"elementTransfer",
                                wrapper:"div",
                                name:"dept",
                                data:[{
                                    value: "1",
                                    label: "aa"
                                },{
                                    key: "2",
                                    value: "bb"
                                }],
                                titles:['未选','已选'],
                                filterable:true 
                            }
                        },{
                            type:"elementSelect",
                            name:"user",
                            label:"用户",
                            transfer:true,
                            multiple:true,
                            source:"options",                        
                            options:this.user,
                            config:{
                                type:"elementTransfer",
                                wrapper:"div",
                                name:"user",
                                data:this.user,
                                titles:['未选','已选'],
                                filterable:true 
                            }
                        }]
                    }                   
                });
            }
        }
    }
</script>
<style>
	.el-button.noText [class*=el-icon-]+span{
		display:none;
	}
</style>
