<template>
    <wrapper
        :is="config.wrapper||'el-form-item'"
        :label="config.label"
        :label-width="config.labelWidth||'0px'"
        @click="click"
        @click.native="click"
        class="elementButton"
        :style="config.style"
    >
        <el-button 
            :type="config.buttonType" 
            :icon="config.icon"
            :round="config.shape=='round'||config.round"
            :circle="config.shape=='circle'||config.circle"
            :plain="config.saturation=='plain'?true:false||config.plain"
            :native-type="config.nativeType"
            :title="config.title"
            :size="config.size"
            :class="{noText:!config.textShow}"
            @click="buttonClick"
        >{{config.text}}</el-button>
    </wrapper>
</template>
<script>
    export default {
        props: ['config','form'],
        mounted(){
            //组件添加删除按钮
            let vue=this,
                span=document.createElement('span');
            span.className="my-close";
            span.addEventListener('click',function(){
                vue.$emit('close',event,vue);
            });
            this.$el.style.position="relative";
            this.$el.appendChild(span);
        },          
        methods:{
            buttonClick: function(event){
                this.$emit('buttonClick',event,this.config);
            },
            click(event){
                let query=this.form&&this.form.query?this.form.query:{"参数":""};
                this.$emit('config',event,this.config,{
                    textShow:{
                        name:"textShow",
                        type:"elementSwitch",
                        label:"显示文字"
                    },
                    text:{
                        name:"text",
                        type:"elementText",
                        label:"文字"
                    },
                    icon:{
                        name:"icon",
                        type:"elementText",
                        label:"图标"
                    },
                    title:{
                        name:"title",
                        type:"elementText",
                        label:"提示"
                    },
                    buttonType:{
                        name:"buttonType",
                        type:"elementSelect",
                        label:"类型",
                        options:[{
                            label:"默认",
                            value:""
                        },{
                            label:"文本",
                            value:"text"
                        },{
                            label:"主要",
                            value:"primary"
                        },{
                            label:"成功",
                            value:"success"
                        },{
                            label:"信息",
                            value:"info"
                        },{
                            label:"警告",
                            value:"warning"
                        },{
                            label:"危险",
                            value:"danger"
                        }]
                    }, 
                    saturation:{
                        name:"saturation",
                        type:"elementRadio",
                        label:"彩度",
                        options:[{
                            type:'el-radio',
                            value:"",
                            label:"鲜艳"
                        },{
                            type:'el-radio',
                            value:"plain",
                            label:"平淡"
                        }]
                    },
                    shape:{
                        name:"shape",
                        type:"elementSelect",
                        label:"形状",
                        options:[{
                            label:"默认",
                            value:""
                        },{
                            label:"圆形",
                            value:"circle"
                        },{
                            label:"圆角",
                            value:"round"
                        }]
                    },                                   
                    size:{
                        name:"size",
                        type:"elementSelect",
                        label:"尺寸",
                        options:[{
                            label:"默认",
                            value:""
                        },{
                            label:"中等",
                            value:"medium"
                        },{
                            label:"小型",
                            value:"small"
                        },{
                            label:"超小",
                            value:"mini"
                        }]
                    },
                    operator:{
                        name:"operator",
                        type:"elementRadioChange",
                        label:"操作",
                        itemDefault:{
                            label:" "
                        },
                        options:[{
                            type:"el-radio",
                            label:"默认",
                            value:"elementSelect", 
                            config:{
                                type:"elementSelect",
                                name:"script",
                                options:[{
                                    value:"this.save(event,config);",
                                    label:"保存"
                                },{
                                    value:"this.cancel(event,config);",
                                    label:"关闭"
                                },{
                                    value:"this.save(event,config,true);",
                                    label:"保存并关闭"
                                },]
                            }                      
                        },{
                            type:"el-radio",
                            label:"自定义",
                            value:"elementTextarea", 
                            config:{
                                name:"script",
                                type:"elementTextarea",                          
                            }                            
                        }]
                    },
                    query:{
                        type:"elementAddDelete",
                        labelPositionTop:true,
                        name:"query",
                        label:"参数",
                        labels:[{
                            label:"参数名"
                        },{
                            label:"参数值"
                        }],
                        itemDefault:{
                            size:"mini",
                            style:"width:40%;display:inline-block;margin-right:2%",
                        },
                        options:query
                    }
                });
            }
        }
    }
</script>
<style>
	.el-button.noText [class*=el-icon-]+span{
		display:none;
	}
</style>
