<template>
    <el-form-item  
        :label="config.label"
        :label-width="config.labelWidth"
        :prop="config.name"
        :rules="rules(config.rules)"
        @click.native="click" 
        :class="{'size-small-font':config.size==='small'||config.size==='mini'?true:false}"
        :style="config.style"
    >
        <el-input 
            v-model.number="form[config.name]"
            :size="config.size"
            :clearable="true" 
            @keyup.enter.native="enter"
            :placeholder="config.placeholder||'请输入'"
            :readonly="config.readonly"
            :disabled="config.disabled"
        ></el-input>
    </el-form-item>
</template>
<script>
    export default {
        props: ['config','form'], 
        created(){
            //默认验证
            this.config.rules=Object.assign({
                required:false,
                trigger:[],
                message:'',
                custom:'pattern'
            },this.config.rules);
        },
        mounted(){
            //组件添加删除按钮
            let vue=this,
                span=document.createElement('span');
            span.className="my-close";
            span.addEventListener('click',function(){
                vue.$emit('close',event,vue);
            });
            this.$el.style.position="relative";
            this.$el.appendChild(span);
        },         
        methods:{
            //验证函数validator与正则验证pattern解析
            rules(rules=[]){   
                let rule=['validator','pattern'];
                for(var key in rules){
                    for(var k in rule){
                        let r=rule[k];
                        if(key==r && rules[key] && typeof(rules[key])=='string'){
                            //eval('rules.'+r+'='+rules[key]+';');
                            eval('rules=Object.assign({},rules,{'+r+':'+rules[key]+'});')
                        }
                        if( rules[key][r] &&  typeof(rules[key][r])=='string'){
                            //eval('rules[key].'+r+'='+rules[key][r]+';');
                            eval('rules[key]=Object.assign({},rules[key],{'+r+':'+rules[key][r]+'});')
                        }
                    }
                }
                return rules;
            },            
            click: function(event){
                this.$emit('config',event,this.config,{
                    name:{
                        type:"elementSelect",
                        label:"字段",
                        name:"name",
                        allowCreate:true,
                        options:[]
                    },
                    label: {
                        type:"elementText",
                        label:"字段名",
                        name:"label"
                    },
                    readonly: {
                        type:"elementSwitch",
                        label:"只读",
                        name:"readonly"
                    },
                    placeholder: {
                        type:"elementText",
                        label:"空白提示",
                        name:"placeholder"
                    },
                    rules:{
                        type:"elementComponents",
                        label:"验证规则",
                        name:"rules",
                        itemDefault:{
                            size:"small"
                        },
                        labelPositionTop:true,
                        form:this.config.rules,
                        options:[{
                            type:"elementSwitch",
                            label:"必填",
                            name:"required",
                        },{
                            type:"elementSelect",
                            label:"类型",
                            name:"type",
                            options:[{
                                label:"数值",
                                value:"number"
                            },{
                                label:"邮箱",
                                value:"email"
                            }]
                        },{
                            type:"elementSelect",
                            label:"触发",
                            name:"trigger",
                            multiple:true,
                            options:[{
                                label:"失去焦点",
                                value:"blur"
                            },{
                                label:"改变",
                                value:"change"
                            }]
                        },{
                            type:"elementText",
                            label:"提示信息",
                            name:"message",
                        },{
                            type:"elementRadioChange",
                            label:"自定义",
                            name:"custom",
                            itemDefault:{
                                size:"small",
                                label:" "
                            },
                            options:[{
                                type:'el-radio',
                                label:"正则",
                                value:"pattern",
                                config:{
                                    type:"elementText",
                                    name:"pattern"
                                }
                            },{
                                type:'el-radio',
                                label:"函数",
                                value:"validator",
                                name:"validator",
                                config:{
                                    type:"elementTextarea",
                                    name:"validator"
                                }
                            }]
                        },]
                    }                                   
                });
            },
            enter(event){
                this.$emit('enter',event,this.config);
            }
        }
    }
</script>
