<template>
    <el-form-item 
        :prop="config.name" 
        :rules="config.rules"
        :label="config.label"
        :label-width="config.labelWidth"
        :class="{'size-small-font':config.size==='small'||config.size==='mini'?true:false}"
        :style="config.style"
        @click.native="click"
    >
        <el-select 
            v-model="form[config.name]" 
            :allow-create="config.allowCreate"
            :multiple="config.multiple"
            :filterable="config.filterable||config.allowCreate" 
            :placeholder="config.placeholder||'请选择'"
            :size="config.size"
            @change="change"
            @click.native="selectClick"
            ref="elementSelect"
        >
            <el-option 
                v-for="opiton in options" 
                value-key="value"
                :key="opiton.value" 
                :label="opiton.label" 
                :value="opiton.value"
            ></el-option>
        </el-select>
		<el-dialog 
            :title="config.label" 
			:visible.sync="transfer" 
			:modal-append-to-body="false" 
			:modal="true"
			:fullscreen="false" 
			:close-on-click-modal="true"
            :showClose="false"
		>
			<elementTransfer :config="config.config" :form="form"></elementTransfer>
			<div slot="footer" class="dialog-footer">
				<!-- <el-button @click="transfer = false">取 消</el-button> -->
				<el-button type="primary" @click="transfer = false">完成</el-button>
			</div>
		</el-dialog>        
    </el-form-item>
</template>
<script>
    export default {
        props: ['config','form'], 
        data(){
            return {
                tables:[],
                fields:[],
                transfer:false,
                options:[]               
            }
        },
        created(){
            this.source(this.config.tableField);
            if(this.config.allowCreate){
                this.$set(this.config,'filterable',true);
            }
            //默认验证
            this.$set(this.config,'rules',Object.assign([{
                required:false,
                trigger:[],
                message:"字段不能为空",
            }],this.config.rules));
        },        
        mounted(){
            //组件添加删除按钮
            let vue=this,
                span=document.createElement('span');
            span.className="my-close";
            span.addEventListener('click',function(){
                vue.$emit('close',event,vue);
            });
            this.$el.style.position="relative";
            this.$el.appendChild(span);
        },
        watch:{
            tableField:{
                handler(newValue,oldValue){
                    this.source(newValue);
                },
                deep:true
            },
            sourceChange(newValue,oldValue){
                this.source(this.config.tableField);
            },
            options(newValue,oldValue){
                this.$set(this.config,'options',newValue);
            }           
        },
        computed:{
            tableField(){
                return this.config.tableField;
            },
            sourceChange(){
                return this.config.source;
            }
        },
        methods: { 
            //options来源处理
            source(tableField){
                if(this.config.source=='tableField' && tableField.table && tableField.fieldLabel && tableField.fieldValue){
                    this.my.axios({
                        vue: this,
                        axiosOption:{
                            url: 'admin/table/table',
                            data:{
                                TABLE_NAME:tableField.table,
                                fields:'`'+tableField.fieldLabel+'` as label,`'+tableField.fieldValue+'` as value',
                            }
                        },
                        success:function(response,option){
                            option.vue.$set(option.vue,'options',response.data.data);

                        }
                    });
                }else{
                    this.options=this.config.options;
                }               
            },                 
            click: function(event){             
                //配置
                if(this.config.source=='tableField' && this.config.tableField){
                    if(!this.tables.length || !this.fields.length){
                        this.my.axiosAll({
                            vue:this,
                            axiosOption:[{
                                url: 'admin/table/tables'
                            },{
                                url: 'admin/table/field',
                                data: {
                                    TABLE_NAME: this.config.tableField.table
                                }
                            }],
                            success:function (response,option) {
                                option.vue.tables=response[0].data.data;
                                option.vue.fields=response[1].data.data;
                                option.vue.emit(event);
                            }
                        });
                    }else{
                        this.emit(event);
                    }
                }else{
                    this.emit(event);
                }

            },  
            emit(event){
                this.$emit('config',event,this.config,{
                    name:{
                        type:"elementSelect",
                        label:"字段",
                        name:"name",
                        allowCreate:true,
                        options:[]
                    },
                    label: {
                        type:"elementText",
                        label:"字段名",
                        name:"label"
                    },
                    source:{
                        type:"elementRadioChange",
                        name:"source",
                        label:"选项来源",
                        script:`
                            if(event=="options"){
                                this.$set(this.attrForm,'options',this.attrForm.options.slice(0,this.attrs.source.options[0].config.options.length));
                            }
                        `,
                        itemDefault:{
                            labelWidth:'0px',
                        },
                        options:[{
                            value:'options',
                            label:'自定义',
                            type:'el-radio',
                            config:{
                                type:"elementAddDelete",
                                name:"options",
                                labels:[{label:'显示值'},{label:'保存值'}],
                                itemDefault:{
                                    style:"width:40%;display:inline-block;margin-right:2%",
                                    size:"mini"
                                },
                                options:Array(this.config.options.length).fill([{
                                    type:"elementText",
                                    name:"label"
                                },{
                                    type:"elementText",
                                    name:"value"
                                }])
                            },
                        },{
                            value:'tableField',
                            label:'表格字段值',
                            type:'el-radio',
                            config:{
                                type:"elementComponents",
                                name:"tableField",
                                itemDefault:{
                                    size:"small"
                                },
                                options:[{
                                    type:"elementSelect",
                                    name:"table",
                                    label:"表格",
                                    allowCreate:true,
                                    options:this.tables,
                                    /*source:"tableField",
                                    tableField:{
                                        table:"INFORMATION_SCHEMA.TABLES",
                                        fieldLabel:"TABLE_COMMENT",
                                        fieldValue:"TABLE_NAME"
                                    },*/
                                    script:`
                                        this.form.tableField.fieldLabel='';
                                        this.form.tableField.fieldValue='';
                                        this.my.axios({
                                            vue: this,
                                            axiosOption:{
                                                url: 'admin/table/field',
                                                data:{
                                                    TABLE_NAME:event
                                                }
                                            },
                                            success:function(response,option){
                                                option.vue.config.options[1].options=response.data.data;
                                                option.vue.config.options[2].options=response.data.data;
                                                if(response.data.data.length){
                                                    option.vue.form.tableField.fieldLabel=response.data.data[0].value;
                                                    option.vue.form.tableField.fieldValue=response.data.data[0].value;                                            
                                                }
                                                
                                            }
                                        });
                                    `
                                },{
                                    type:"elementSelect",
                                    name:"fieldLabel",
                                    label:"显示值",
                                    allowCreate:true,
                                    options:this.fields,
                                },{
                                    type:"elementSelect",
                                    name:"fieldValue",
                                    label:"保存值",
                                    allowCreate:true,
                                    options:this.fields,
                                }]
                            }
                        }]
                    },
                    filterable:{
                        type:"elementSwitch",
                        label:"允许搜索",
                        name:"filterable"
                    },
                    allowCreate:{
                        type:"elementSwitch",
                        label:"允许创建",
                        name:"allowCreate"
                    },
                    rules:{
                        type:"elementComponents",
                        label:"验证规则",
                        name:"rules",
                        itemDefault:{
                            size:"small",
                            //style:"border-bottom:1px solid #eee;margin-bottom:10px;padding-bottom:10px;"
                        },
                        labelPositionTop:true,
                        options:[{
                            type:"elementComponents",
                            labelWidth:"0px",
                            name:"0",
                            itemDefault:{
                                size:"small"
                            },
                            options:[{
                                type:"elementSwitch",
                                label:"必填",
                                name:"required",
                            },{
                                type:"elementSelect",
                                label:"触发",
                                name:"trigger",
                                multiple:true,
                                options:[{
                                    label:"失去焦点",
                                    value:"blur"
                                },{
                                    label:"改变",
                                    value:"change"
                                }]
                            },{
                                type:"elementText",
                                label:"提示信息",
                                name:"message",
                            }]
                        }]
                    }                     
                });
            },
            change(value){
                this.$emit('selectChange',value,this.config);
                this.$emit('e',value,this.config);
            },
            selectClick(event){
                if(this.config.transfer){
                    this.$refs.elementSelect.blur();
                    this.transfer=true;
                }
            }            
        }   
    }
</script>
<style>
</style>
