<template>
    <el-form-item 
        :label="config.label"
        :label-width="config.labelWidth"
        :prop="config.name"
        :rules="rules"
        @click.native="click"
    >
        <el-input 
            type="textarea" 
            v-model="form[config.name]" 
            :clearable="true" 
            :readonly="config.readonly"
            :rows="config.rows"
            :autosize="config.autosize"
            :placeholder="config.placeholder||'请输入'"
        ></el-input>
    </el-form-item>
</template>
<script>
    export default {
        props: ['config','form'],
        created(){
            //默认验证
            this.$set(this.config,'rules',Object.assign([{
                required:false,
                trigger:[],
                message:"字段不能为空",
            },{
                type:'',
                trigger:[],
                message:'',
            },{
                custom:'pattern',
                trigger:[],
                message:'',
            }],this.config.rules));
        },
        mounted(){
            //组件添加删除按钮
            let vue=this,
                span=document.createElement('span');
            span.className="my-close";
            span.addEventListener('click',function(){
                vue.$emit('close',event,vue);
            });
            this.$el.style.position="relative";
            this.$el.appendChild(span);
        },
        computed:{
            //验证函数validator与正则验证pattern解析            
            rules(){
                let rules=this.config.rules;
                if(rules){
                    let rule=['validator','pattern'];
                    for(var k in rule){
                        let r=rule[k];
                        if(rules[r]){
                            try{
                                eval('rules=Object.assign({},rules,{'+r+':'+rules[r]+'});');
                            }catch(e){
                                console.log(e);
                            }
                        }
                        if(rules[2] && rules[2][r]){
                            try{
                                eval('rules=Object.assign([],rules,{'+2+':{'+r+':'+rules[2][r]+'}});')
                            }catch(e){
                                console.log(e);
                            }
                        }
                    }
                }
                return rules;
            }
        },      
        methods:{         
            click: function(event){
                this.$emit('config',event,this.config,{
                    name:{
                        type:"elementSelect",
                        label:"字段",
                        name:"name",
                        allowCreate:true,
                        options:[]
                    },
                    label: {
                        type:"elementText",
                        label:"字段名",
                        name:"label"
                    },
                    readonly: {
                        type:"elementSwitch",
                        label:"只读",
                        name:"readonly"
                    },
                    placeholder: {
                        type:"elementTextarea",
                        label:"空白提示",
                        name:"placeholder"
                    },
                    autosize:{
                        type:"elementComponents",
                        label:"自动尺寸",
                        name:"autosize",
                        itemDefault:{
                            size:"mini",
                            labelWidth:'65px'
                        },
                        options:[{
                            name:"minRows",
                            label:"最小行数",
                            type:"elementInputNumber",
                            script:"console.log(this.form,this.config)"
                        },{
                            name:"maxRows",
                            label:"最大行数",
                            type:"elementInputNumber"
                        }]
                    },
                    rules:{
                        type:"elementComponents",
                        label:"验证规则",
                        name:"rules",
                        itemDefault:{
                            size:"small",
                            style:"border-bottom:1px solid #eee;margin-bottom:10px;padding-bottom:10px;"
                        },
                        labelPositionTop:true,
                        options:[{
                            type:"elementComponents",
                            labelWidth:"0px",
                            name:"0",
                            itemDefault:{
                                size:"small"
                            },
                            options:[{
                                type:"elementSwitch",
                                label:"必填",
                                name:"required",
                            },{
                                type:"elementSelect",
                                label:"触发",
                                name:"trigger",
                                multiple:true,
                                options:[{
                                    label:"失去焦点",
                                    value:"blur"
                                },{
                                    label:"改变",
                                    value:"change"
                                }]
                            },{
                                type:"elementText",
                                label:"提示信息",
                                name:"message",
                            }]
                        },{
                            type:"elementComponents",
                            labelWidth:"0px",
                            name:"1",
                            itemDefault:{
                                size:"small"
                            },
                            options:[{
                                type:"elementSelect",
                                label:"类型",
                                name:"type",
                                options:[{
                                    label:"字符",
                                    value:"string"
                                },{
                                    label:"邮箱",
                                    value:"email"
                                },{
                                    label:"url地址",
                                    value:"url"
                                },{
                                    label:"正则表达式",
                                    value:"regexp"
                                },{
                                    label:"函数",
                                    value:"method"
                                }]
                            },{
                                type:"elementSelect",
                                label:"触发",
                                name:"trigger",
                                multiple:true,
                                options:[{
                                    label:"失去焦点",
                                    value:"blur"
                                },{
                                    label:"改变",
                                    value:"change"
                                }]
                            },{
                                type:"elementText",
                                label:"提示信息",
                                name:"message",
                            }]
                        },{
                            type:"elementComponents",
                            labelWidth:"0px",
                            name:"2",
                            itemDefault:{
                                size:"small"
                            },
                            options:[{
                                type:"elementRadioChange",
                                label:"自定义",
                                name:"custom",
                                itemDefault:{
                                    size:"small",
                                    label:" "
                                },
                                options:[{
                                    type:'el-radio',
                                    label:"正则",
                                    value:"pattern",
                                    config:{
                                        type:"elementText",
                                        name:"pattern",
                                        /*rules:{
                                            2:{
                                                custom:"validator",
                                                trigger:["change"],
                                                validator: `
                                                    function(rule, value, callback){
                                                        if(value){
                                                            try{
                                                                eval('let test='+value+';');
                                                                callback();
                                                            }catch(e){
                                                                callback(new Error('格式错误,'+e));
                                                            }
                                                        }else{
                                                            callback();
                                                        }
                                                    }`
                                            }
                                        }*/
                                    }
                                },{
                                    type:'el-radio',
                                    label:"函数",
                                    value:"validator",
                                    config:{
                                        type:"elementTextarea",
                                        name:"validator",
                                        /*rules:{
                                            2:{
                                                custom:"validator",
                                                trigger:["change"],
                                                validator: `
                                                    function(rule, value, callback){
                                                        if(value){
                                                            try{
                                                                eval('let test='+value+';');
                                                                callback();
                                                            }catch(e){
                                                                callback(new Error('格式错误,'+e));
                                                            }
                                                        }else{
                                                            callback();
                                                        }
                                                    }`
                                            }
                                        }*/
                                    }
                                }]
                            },{
                                type:"elementSelect",
                                label:"触发",
                                name:"trigger",
                                multiple:true,
                                options:[{
                                    label:"失去焦点",
                                    value:"blur"
                                },{
                                    label:"改变",
                                    value:"change"
                                }]
                            },{
                                type:"elementText",
                                label:"提示信息",
                                name:"message",
                            }]
                        }]
                    }                                                      
                });
            },
            enter(event){
                this.$emit('enter',event,this.config);
            }
        }
    }
</script>
