<template>
    <el-form-item 
        label-width="0px"
        @click.native="click"
    >
        <el-button 
            :type="config.buttonType" 
            @click="buttonClick"
            :icon="config.icon"
            :round="config.shape=='round'||config.round"
            :circle="config.shape=='circle'||config.circle"
            :plain="config.shape=='plain'||config.plain"
            :native-type="config.nativeType"
            :title="config.title"
            :size="config.size"
            class="elementButton"
        >{{config.text}}</el-button>
    </el-form-item>
</template>
<script>
    export default {
        props: ['config'],
        methods:{
            buttonClick: function(event){
                this.$emit('buttonClick',event,this.config);
            },
            click(event){
                this.$emit('config',event,this.config,{
                    text:{
                        name:"text",
                        type:"elementText",
                        label:"文字"
                    },
                    icon:{
                        name:"icon",
                        type:"elementText",
                        label:"图标"
                    },
                    title:{
                        name:"title",
                        type:"elementText",
                        label:"提示"
                    },
                    buttonType:{
                        name:"buttonType",
                        type:"elementSelect",
                        label:"类型",
                        options:[{
                            label:"默认",
                            value:""
                        },{
                            label:"主要",
                            value:"primary"
                        },{
                            label:"成功",
                            value:"success"
                        },{
                            label:"信息",
                            value:"info"
                        },{
                            label:"警告",
                            value:"warning"
                        },{
                            label:"危险",
                            value:"danger"
                        }]
                    }, 
                    shape:{
                        name:"shape",
                        type:"elementSelect",
                        label:"形状",
                        options:[{
                            label:"默认",
                            value:""
                        },{
                            label:"普通",
                            value:"plain"
                        },{
                            label:"圆形",
                            value:"circle"
                        },{
                            label:"圆角",
                            value:"round"
                        }]
                    },                                   
                    size:{
                        name:"size",
                        type:"elementSelect",
                        label:"尺寸",
                        options:[{
                            label:"默认",
                            value:""
                        },{
                            label:"中等",
                            value:"medium"
                        },{
                            label:"小型",
                            value:"small"
                        },{
                            label:"超小",
                            value:"mini"
                        }]
                    },
                    operator:{
                        name:"operator",
                        type:"elementRadioChange",
                        label:"操作",
                        options:[{
                            type:"el-radio",
                            label:"默认",
                            value:"elementSelect", 
                            config:{
                                type:"elementSelect",
                                name:"script",
                                label:' ',
                                options:[{
                                    value:"this.save(event,config);",
                                    label:"保存"
                                },{
                                    value:"this.cancel(event,config);",
                                    label:"关闭"
                                },{
                                    value:"this.save(event,config,true);",
                                    label:"保存并关闭"
                                },]
                            }                      
                        },{
                            type:"el-radio",
                            label:"自定义",
                            value:"elementTextarea", 
                            config:{
                                name:"script",
                                label:' ',
                                type:"elementTextarea",                          
                            }                            
                        }]
                    }                    
                });
            }
        }
    }
</script>
<style>
	.el-form-item .el-button [class*=el-icon-]+span{
		margin-left: 0px;
	}
</style>
